/*
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <bits/stdc++.h>
using namespace std;
typedef long long ll;

ll even_fibonacci(int n) {
    ll a = 1, b = 2, c, sum = 0LL;
    while(a+b < n) {
        c = a+b;
        a = b;
        b = c;
        if((c%2) == 0) sum += c;
    }
    return sum+2;
}

int main() {
    freopen("../in.in", "r", stdin);
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    int n; cin >> n;
    cout << even_fibonacci(n) << "\n";
    return 0;
}

